name: expense_categoriser
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  csv: ^5.0.2
  file_picker: ^5.2.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
